user_agent = "Safari is the best!"
stop_words = [ "è»", "éƒ­æ¥ ", "é”…ç”·", "èˆæ¥ ", "å›½é’•", "ä¸‹å¤´", "æ™®ä¿¡ç”·", "æ™®ä¿¡å¥³", "æ™®ä¸”ä¿¡", "å¥‡è¶£è›‹", "é’“é±¼", "ç¡¬é’“", "å·¨å©´", "çƒ‚è£¤è£†", "å¥½è£¤è£†", "è£¤è£†é‰´å®š", "å°ä»™å¥³", "å©Šå­", "å¤šå°‘æ²¾ç‚¹", "å·®ä¸å¤šå¾—äº†", "å‚»é€¼", "å•¥æ¯”", "å‚»b", "ä¼å…µ", "å‚»åµ", "å•Šå¯¹å¯¹å¯¹", "å¼±æ™º", "è„‘ç˜«", "æ€¥äº†æ€¥äº†", "æœ‰ç—…", "ğŸ˜…", "ç²‰è›†", "å°ç²‰çº¢", "å‚»å®", "ç¥è›†", "ç¥ç¥", "å…”å…”", "çº¦ç‚®", "è´µç‰©", "çŸ³ç ¸ç‹—å«", "çŸ³ç ¸ğŸ¶å«", "â›µ", "å‹¾å…«", "å‹¾8", "j8", "å´½ç§", "åŸæ‰¹", "èˆŸèˆŸäºº", "ç²¥ç²¥äºº", "å†œæ‰¹", "å†œp", "åŸp", "ğŸ˜˜", "ç¿æ™º", "ä¸ˆè‚²", "ğŸ¤ª", "ä½ å¦ˆçš„", "å‡ æŠŠ", "å¥½ä¼¼", "å¥½æ­»", "çƒ§é¸¡", "éªšé¸¡", "ç®¡å¥½ä½ è‡ªå·±",]
care_words = ["æƒ³è‡ªæ€", "æƒ³è·³æ¥¼", "æƒ³å‰²è…•", "ä¼šè‡ªæ€", "ä¼šè·³æ¥¼", "ä¼šå‰²è…•", "è¦è‡ªæ€", "è¦è·³æ¥¼", "è¦å‰²è…•", "æ‰“ç®—è‡ªæ€", "æ‰“ç®—è·³æ¥¼", "æ‰“ç®—å‰²è…•", "æ­»æ³•", "å†è§ä¸–ç•Œ", "å†è§äº†è¿™ä¸ªä¸–ç•Œ", "æ°¸åˆ«", "æ¥ä¸–å†è§", "æ­»äº¡", "è·³ä¸‹å»", "ä¸æƒ³æ´»", "æŠ‘éƒ", "åŒç›¸", "ç»æœ›", "ç»“æŸç—›è‹¦"]
change_log = "æ—¦æŒæ ¡å›­åŠ©æ‰‹ 1.4.9 å·²ç»å‘å¸ƒã€‚è¿™æ˜¯æˆ‘ä»¬è¿‘ä¸€å¹´æ¥æœ€å¤§çš„æ›´æ–°ï¼ŒåŒ…æ‹¬å®Œå…¨é‡å†™çš„ç½‘ç»œæ ˆä»¥åŠå¯¹æ–°ç³»ç»Ÿçš„æ¥å£é€‚é…ï¼Œå¹¶ä¿®å¤äº†å¤§é‡é—ç•™é—®é¢˜ã€‚è¯·ç›´æ¥ç‚¹å‡»ä¸‹é¢çš„æŒ‰é’®è·³è½¬å®˜ç½‘ä¸‹è½½ï¼Œä¹Ÿå¯ä»¥ç›´æ¥ç”¨æµè§ˆå™¨è®¿é—® danxi.fduhole.comï¼Œé€‰æ‹©ã€Œé¡¹ç›®ã€-ã€Œæ ¡å›­åŠ©æ‰‹ã€ä»¥ä¸‹è½½ã€‚"

highlight_tag_ids = [15698]

[[dev_notice]]
updated_at = "2025-06-05T16:30:00+0800"
content = "æœ€è¿‘æˆ‘ä»¬è¿è¥çš„èŒ¶æ¥¼ç­‰æœåŠ¡é¢‘å‘è¿ç»´äº‹ä»¶ï¼Œç»™ä¸€éƒ¨åˆ†åŒå­¦å¸¦æ¥äº†ä¸å¤ªå¥½çš„ä½¿ç”¨ä½“éªŒã€‚\n\nå› æ­¤ï¼Œæˆ‘ä»¬ä¸Šçº¿äº†æ—¦æŒæœåŠ¡çŠ¶æ€é¡µï¼Œå¯ä»¥åœ¨è¿™é‡Œäº†è§£åˆ°è¿ç»´çš„æœ€æ–°äº‹ä»¶ã€å…·ä½“æŠ€æœ¯åŸå› ã€ä¿®å¤è¿›ç¨‹ã€‚æ¬¢è¿å¤§å®¶è®¿é—®ï¼š\n\nhttps://uptime.fduhole.com/"
build = 999

[[dev_notice]]
updated_at = "2025-05-20T13:00:00+0800"
content = "è¿‘æœŸï¼Œæˆ‘ä»¬å‘ç°ä¿¡æ¯åŠæ›´æ–°äº† UIS çš„ç™»å½•æ–¹å¼ï¼Œå¯¼è‡´å¾ˆå¤šåŒå­¦åœ¨ Windows / Android / Linux ç«¯æ— æ³•ç™»å½• UISï¼Œæç¤ºã€Œè¶…æ—¶ã€ç­‰é”™è¯¯ã€‚è¯¥é—®é¢˜å·²ç»åœ¨å†…æµ‹ç‰ˆä¿®å¤ã€‚å¦‚æœé‡åˆ°ï¼Œè¯·ä»ç™»å½•ç•Œé¢ç‚¹å‡»ã€Œæ— æ³•ç™»å½•ï¼Ÿã€åŠ å…¥å†…æµ‹ç¾¤ï¼Œåœ¨ç¾¤æ–‡ä»¶ä¸­è·å–æœ€æ–°ç‰ˆæœ¬ã€‚æ–°çš„æ­£å¼ç‰ˆä¹Ÿå°†ä¸æ—¥å‘å¸ƒã€‚"
build = 345

[[dev_notice]]
updated_at = "2025-06-09T23:20:00+0800"
content = "æ›´æ–°æ—¦æŒ 1.4.8 çš„åŒå­¦ï¼ˆä¸å« Apple ç”¨æˆ·ï¼‰ï¼Œå¦‚æœå‘ç°ä»æ— æ³•æ­£å¸¸è·å–è¯¾è¡¨ï¼Œå¯ä»¥å°è¯•é€€å‡º UIS é‡æ–°ç™»å½•ã€å¸è½½åº”ç”¨é‡è£…æˆ–æ¸…é™¤åº”ç”¨æ•°æ®ã€‚\n\næ–°ç‰ˆå°†ã€Œè®¾ç½®ã€å…¥å£ç§»åŠ¨åˆ°äº†é¦–é¡µå³ä¸Šè§’ï¼Œè¿˜è¯·æ³¨æ„ã€‚\n\nï¼ˆç›¸åŒçš„è¯´æ˜åœ¨æ›´æ–°å…¬å‘Šä¸­ä¹Ÿæœ‰ï¼Œè¿™é‡Œå†å‘ä¸€éã€‚ï¼‰"
build = 345

[[dev_notice]]
updated_at = "2025-06-29T00:40:00+0800"
content = "ç”±äºå¤æ—¦ä¿¡æ¯åŠçªç„¶æ›´æ”¹å¤§éƒ¨åˆ†ç™»å½•æ¥å£ï¼Œç›®å‰æ ¡å†…æœåŠ¡ï¼ˆé¦–é¡µå¤§éƒ¨åˆ†åŠŸèƒ½åŠ UIS ç™»å½•è®¤è¯ï¼‰å‡æ— æ³•ä½¿ç”¨ã€‚\n\næˆ‘ä»¬æ­£åœ¨é‡æ–°ç†Ÿæ‚‰æ–°æ¥å£çš„å½¢å¼ï¼Œé¢„è®¡è‡³å°‘éœ€è¦ä¸€å‘¨ä»¥ä¸Šæ—¶é—´æ‰èƒ½å‘å¸ƒæ–°ç‰ˆã€æ¢å¤æœåŠ¡ã€‚\n\nåœ¨æ­¤æœŸé—´å†…ï¼Œå¦‚æœ Android/Windows ç”¨æˆ·æ— æ³•ç™»å½• UISï¼ˆç†è®ºä¸Šæˆ‘ä»¬æœ‰è¿˜èƒ½ä½¿ç”¨çš„å¤‡ç”¨æ¥å£ï¼Œå¯ä»¥å¤šé‡è¯•ç™»å½•å‡ æ¬¡ï¼‰ï¼Œå¯ä»¥ä½¿ç”¨ã€Œä»…èŒ¶æ¥¼ã€æ¨¡å¼è®¿é—®èŒ¶æ¥¼ã€‚WebVPN åŠŸèƒ½å¯èƒ½ä¹Ÿæ— æ³•ä½¿ç”¨ï¼Œå› æ­¤ä½ å¯èƒ½éœ€è¦è‡ªå¤‡ EasyConnect åœ¨æ ¡å¤–è®¿é—®ã€‚\n\nå¦å¤–ï¼Œã€Œä»…èŒ¶æ¥¼ã€æ¨¡å¼ç›®å‰æœ‰ä¸ªå° bugï¼Œæ— æ³•è¿›å…¥è®¾ç½®é¡µé¢ã€‚æˆ‘ä»¬ä¼šå¾ˆå¿«å‘å¸ƒæ–°ç‰ˆä¿®å¤æ­¤é—®é¢˜ã€‚"
build = 345

[[dev_notice]]
updated_at = "2025-09-07T23:38:00+0800"
content = "ç»è¿‡ä¸€ä¸ªå‡æœŸçš„åŠªåŠ›ï¼ŒFlutter ç«¯ï¼ˆAndroid / Linux / Windowsï¼‰çš„å¤æ—¦ç›¸å…³æ¥å£çš„ç»´ä¿®å·¥ä½œå·²æ¥è¿‘å°¾å£°ã€‚æˆ‘ä»¬å°†ç›®å‰å·²çŸ¥çš„æƒ…å†µæ€»ç»“å¦‚ä¸‹ï¼š\n\nè€ƒè¯•ä¸æˆç»©åŠŸèƒ½ï¼šå°šæœªä¿®å¤\n\nå…¶ä»–å¤æ—¦ç›¸å…³åŠŸèƒ½ï¼ˆç™»å½•ã€è¯¾è¡¨ã€é¦–é¡µå„é¡¹åŠŸèƒ½â€¦â€¦ï¼‰ï¼šå·²ä¿®å¤ï¼Œå³å°†å‘å¸ƒ\n\nèŒ¶æ¥¼ï¼šå›¾ç‰‡ä¸Šä¼ ã€å›¾ç‰‡æŸ¥çœ‹å’Œè·å– tags ç›®å‰å¯èƒ½æ— æ³•å·¥ä½œï¼Œä¸ºæ–°è¿‘å‘ç”Ÿçš„åç«¯é—®é¢˜ï¼Œæ­£åœ¨æ£€ä¿®ä¸­ã€‚å…¶ä»–åŠŸèƒ½æ­£å¸¸\n\næ˜å¤©æ–°å­¦æœŸå¼€å­¦ï¼ŒFlutter ç«¯çš„æ–°ç‰ˆæœ¬ä¹Ÿå°†åœ¨æœ€è¿‘ä¸¤æ—¥å†…å‘å¸ƒã€‚æ„Ÿè°¢å¼€å‘ç»„å„ä¸ªåŒå­¦æŠ½å‡ºå¤§é‡ä¸šä½™æ—¶é—´è¿›è¡Œç»†è‡´è€å¿ƒçš„å¤§é‡å·¥ä½œï¼Œä¹Ÿæ„Ÿè°¢å„ä½åŒå­¦çš„é™ªä¼´å’Œç­‰å¾…ï¼\n\nå¦å¤–ï¼Œä¹Ÿæ¬¢è¿å„ä½æ„¿æ„æµ‹è¯•æ–°ç‰ˆæœ¬çš„åŒå­¦åŠ å…¥ QQ å†…æµ‹ç¾¤ï¼Œæå‰è·å–æœ€æ–°å†…æµ‹ç‰ˆæœ¬ã€æä¾›ä¸€çº¿åé¦ˆï¼š941342818"
build = 345

[[banners]]
title = "å¿ƒå‘æœ¬è‰ï¼Œä¸€å¶çŸ¥ç§‹"
action = "https://mp.weixin.qq.com/s/r3NT1B2YQpV-8YvZTyp7TQ"
button = "å¯»èŠ³è€Œè‡³"

[[banners]]
title = "æ¥PCSå½“å¤æ—¦ç”µè„‘éª‘å£«ï¼"
action = "https://mp.weixin.qq.com/s/a466fg3AL2kzEY6EEoeelQ"
button = "æˆ‘çœŸå¹¸è¿"


[[banners]]
title = "æ¬¢è¿åŠ å…¥å¤æ—¦é£ç›˜ç¤¾"
action = "#502436"
button = "äº†è§£è¯¦æƒ…"

[[banners]]
title = "å¿äº‘å¼“ç¤¾ï¼Œå¼“å€™å›ä¸´"
action = "https://mp.weixin.qq.com/s/9kTzsjNN0j2stT4Vzqixhg"
button = "ç«‹å³èµ·å°„"

[[banners]]
title = "èŒ¶æ¥¼æ¨ªå¹…ä½ç”³è¯·æŒ‡å—"
action = "https://danxi-dev.feishu.cn/wiki/NfSfwq5I2izsbbkTcNdcnbgXnrf"	
button = "ç‚¹å‡»æŸ¥çœ‹"

[[banners]]
title = "å¿ƒèˆæ‹›æ–°| ä»¥èˆä¹‹åï¼Œèµ´ä½ ä¹‹çº¦"
action = "#508317"	
button = "ä¸å¦‚è·³èˆ"

[semester_start_date]
504 = "2025-09-08" # 25-26ä¸Š
487 = "2025-02-17" # 24~25ä¸‹
485 = "2024-09-02" # 24~24ä¸Š
484 = "2024-07-01" # 24æš‘
464 = "2024-02-26" # 23~24ä¸‹
444 = "2023-09-04" # 23~24ä¸Š
425 = "2023-02-20" # 22~23ä¸‹
404 = "2022-09-05" # 22~23ä¸Š
387 = "2022-02-21" # 21~22ä¸‹

[[celebrations]]
date = "01-02"
words = [ "æœ‰äººä¸€ä¸ªäººè·¨å¹´ï¼Œæˆ‘ä¸è¯´æ˜¯è°", "æœ‰äººåœ¨è·¨å¹´å¤œå¤ä¹ ï¼Œæˆ‘ä¸è¯´æ˜¯è°", "æœ‰äººä¸¤ä¸ªäººè·¨å¹´ä½†åˆ†åˆ«å¤ä¹ ï¼Œæˆ‘ä¸è¯´æ˜¯è°", "æœ‰äººè€ƒå®Œäº†ä½†è·¨å¹´å¤œè¿˜åœ¨å†™è®ºæ–‡ï¼Œæˆ‘ä¸è¯´æ˜¯è°", "æœ‰äººå¿˜è®°å…³ä¿¡æ¯åŠæˆç»©æé†’äº†ï¼Œæˆ‘ä¸è¯´æ˜¯è°", "æ‚²æŠ¥ï¼šç®¡ç†å‘˜ä»Šå¤©ä¸ä¸Šç­ğŸ˜­", "å–œæŠ¥ï¼šç®¡ç†å‘˜ç°åœ¨è¿˜æ²¡è€ƒå®ŒğŸ˜­", "å–œæŠ¥ï¼šæ—¦å¤•å›¢é˜Ÿ2023å¹´å‘ç”Ÿ0èµ·æ¬ è–ªäº‹ä»¶ï¼", "ä¸è¿œäº†ï¼Œä¸è¿œäº†â€¦â€¦", "å†·çŸ¥è¯†ï¼š11å’Œ23æ˜¯2024çš„å› å­",]

[[celebrations]]
date = "é™¤å¤•"
words = [ "çªå‡»æ£€æŸ¥ï¼šæœ‰æ²¡æœ‰åœ¨çœ‹æ˜¥æ™š", "çªå‡»æ£€æŸ¥ï¼šæœ‰æ²¡æœ‰å›å®¶è¿‡å¹´", "å¥½è€¶ï¼Œé©¬ä¸Šå°±è¦è¿‡å¹´å’¯~", "ã€é¥ºå­ã€‘ã€é¥ºå­ã€‘ã€é¥ºå­ã€‘", "æ®‹è…Šå³åˆå°½ï¼Œä¸œé£åº”æ¸é—»", "ã€æ±¤åœ†ã€‘ã€æ±¤åœ†ã€‘ã€æ±¤åœ†ã€‘", "çªå‡»æ£€æŸ¥ï¼šäº”ç¦é›†é½äº†å—", "å–œæŠ¥ï¼šç®¡ç†å‘˜é™¤å¤•ä¹Ÿä¸æ”¾å‡ï¼ï¼ï¼", "æ ‘æ´çš„æœ‹å‹ä»¬ï¼Œæˆ‘æƒ³æ­»ä½ ä»¬å•¦â€”â€”", "æ—¦å¤•å†°çº¢èŒ¶ï¼Œä¸€ç™¾å…«ä¸€æ¯",]

[[celebrations]]
date = "æ˜¥èŠ‚"
words = [ "å¾…åˆ°å±±èŠ±çƒ‚æ¼«æ—¶ï¼Œå¥¹åœ¨ä¸›ä¸­ç¬‘", "ä¸é¡»è¿å‘ä¸œéƒŠå»ï¼Œæ˜¥åœ¨åƒé—¨ä¸‡æˆ·ä¸­ã€‚ğŸ†", "æ¾ç«¹å«æ–°ç§‹ï¼Œè½©çª—æœ‰ä½™æ¸…ã€‚", "é½é¼“éš†å†¬å¼ºä¸œå¼ºï¼", "æ—¦å¤•èŒ¶é¦†ï¼Œæ˜¥èŠ‚ä¹Ÿå¼€æ”¾", "æ¥æ—¦å¤•èŒ¶é¦†ä¸€èµ·åŒ…é¥ºç ¸ï¼", "æ¥æ—¦å¤• App å­¦ä¹ ç¥ç¦è¯­", "æ–°å¹´å¥½å‘€ï¼Œæ–°å¹´å¥½å‘€ï¼Œç¥ç¦å¤§å®¶æ–°å¹´å¥½â™ª", "æ„¿å¾—é•¿å¦‚æ­¤ï¼Œå¹´å¹´ç‰©å€™æ–°", "æå‰385å¤©ç¥å¤§å®¶é¾™å¹´å¤§å‰ï¼", "è´¢ç¥æ¥åˆ°æˆ‘ï¼å®¶ï¼é—¨ï¼æ—¦å¤•æ¥ï¼ç‚¹ï¼ç¯ï¼", "æ­å–œæ­å–œæ­å–œä½ å•Šæ­å–œæ­å–œæ­å–œä½ ", "å–œæŠ¥ï¼šç®¡ç†å‘˜æ˜¥èŠ‚ä¸Šç­ä¸‰å€å·¥èµ„ï¼ï¼ˆ3*0=0ï¼‰", "SGFwcHkgc3ByaW5nIGZlc3RpdmFsIQ==", "çˆ†ç«¹å£°ä¸­ä¸€å²é™¤ï¼Œæ˜¥é£é€æš–å…¥å± è‹ï¼ï¼ˆå‡è£…å¯ä»¥ç‡ƒæ”¾çƒŸèŠ±çˆ†ç«¹QwQï¼‰", "",]

[[celebrations]]
date = "04-01"
words = [ "å˜‰ç„¶ä»Šå¤©åƒæ‰äº†ä½ çš„è„‘å­", "è’™å¤ä¸Šå•å¤§æˆ˜å¸å›½æµ·å†›", "æ—¦æŒæŒ–çŸ¿ä¸­â€¦â€¦", "æ—¥â†’æœˆâ†˜å…‰â†—åâ†˜å…±â†˜ç¿â†˜çƒ‚â†—â†—â†—â†—", "å•Šâ™‚ä¸€èµ·æ¥vanæ¸¸æˆ", "ç¦€æŠ¥ç®¡ç†å‘˜ï¼Œæ ‘æ´é©¾å´©å•¦â€”â€”â€”", "æ‰«ç çœ‹ç®¡ç†å‘˜å¥³è£…", "ğŸ˜…+ç”µé£æ‰‡==ğŸ˜„", "æˆ‘å‘½ä»¤ä½ GPA4.0", "å°±ç®—å¤§é›¨è®©è¿™åº§åŸå¸‚é¢ å€’ï¼Œæˆ‘ä¹Ÿè¦å»åˆ·é”»", "æ—¦æŒ AI å¤§æ¨¡å‹éœ‡æ’¼ç™»åœº", "æ­£åœ¨æ¥ç®¡äººç±»ç»Ÿæ²»æƒâ€¦â€¦", "æˆ‘æ˜¯ç¬¬ä¸€æ¡", "æˆ‘æ˜¯ç¬¬äºŒæ¡", "æ™šä¸Šåï½", "åŸç¥ï¼Œå¯åŠ¨ï¼", "è¿™é‡Œæ˜¯äº¤å¤§ï¼Œè¯¥æ»šçš„æ˜¯ä½ ä»¬å¤æ—¦å§ï¼Ÿ", "ç¬‘ç‚¹è§£æï¼šæè§£ç‚¹ç¬‘", "Look in my eyes!ğŸ‘", "rm -rf /*", "ï¼Œä½ è¿æ¬¢", "ä¸ºä»€ä¹ˆå‘¢ï¼Ÿ", "ä¸æ‡‚ï¼Œæˆ‘ç©ç»´ä»€æˆ´å°”/æ°´é¾™ç‹/éè¶çš„", "è¯¥å¡«å¹³å®‰å¤æ—¦äº†", "è¯•é—®ï¼Œä½ æ˜¯æˆ‘çš„masterå—ï¼Ÿ", "çŒ«çŒ«åƒæ‰äº†ä½ çš„è„‘å­ï¼", "test", "lorem ipsum dolor sit amet", "ç‚¹å‡»è¿™è¡Œæ–‡å­—å¿«è¿›åˆ°æš‘å‡", "éœ‡æƒŠï¼æŸå¤æ—¦å­¦å­å‘ç°æ°¸åŠ¨æœºï¼Œç‰©ç†ç³»è¿å¤œè¾Ÿè°£", "å›å¤â€˜æˆ‘çˆ±å­¦ä¹ â€™è§£é”ç®¡ç†å‘˜éšè—è¡¨æƒ…åŒ…", "å…¥æ ¡æƒé™âŒ", "ä»Šæ›°çš„è¯¾ç¨‹å·²å…¨éƒ¨ç»“æœ«", "åˆ·èŒ¶æ¥¼ä¼šå½±å“ä½ çš„è®¡ç®—æœºæ€ç»´ï¼", "æˆ‘ä»¬å¾®ç”µå­ä¸é€†å¤©.jpg", "åå’Œæ”¾å®½", "æˆ‘æ²’æœ‰èªªéé€™å¥è©±", "å“å‘€âœ‹ğŸ»ğŸ¤šğŸ»æ¥¼å¾—äº†MVP", "èŒ¶æ¥¼å°±æ˜¯èººèµ¢ç‹—â†“ï¼Œä»Šå¤©çš„è¯„åˆ†â†‘â†“3.0", "no ons no admin, å…¬çº¦ä¸Šä¹Ÿæ˜¯è¿™æ ·è®°è½½çš„", "tell me why baby",]

[latest_version]
# swift = "2.0.6" # swift ç‰ˆä¸å†éœ€è¦è¿™ä¸€å­—æ®µ
flutter = "1.4.9"

[[sticker]]
id = "dx_murderous"
sha256 = "8b3b899c3a14d08dafc3a791d58444065f071d494d83c828620551e21e6c0afe"
url = "https://image.fduhole.com/i/2025/05/23/683022b372d1eb.webp"

[[sticker]]
id = "dx_roll"
sha256 = "125295473869dc160d94ccfd0d7a02d25267cf9217ba946d20c3f30bac25cde6"
url = "https://image.fduhole.com/i/2025/05/23/683022b4ec4630.webp"

[[sticker]]
id = "dx_call"
sha256 = "ebe6179b6c60fbf22dea5a11efa4634b0239564acf3e7e7a55e2cbb86f4991aa"
url = "https://image.fduhole.com/i/2025/05/23/683022b404e259.webp"

[[sticker]]
id = "dx_rush"
sha256 = "6a10000441a3563bc7f090f4db9853bf61c1a5e46edab06414418c1f925fad0f"
url = "https://image.fduhole.com/i/2025/05/23/683022b4895a27.webp"

[[sticker]]
id = "dx_guilty"
sha256 = "6cb147466609ce0ce984ab5f978b99be69bb133a5bc4bc9d55cfb52b8bcfa663"
url = "https://image.fduhole.com/i/2025/05/23/683022b45b7f67.webp"

[[sticker]]
id = "dx_kiss"
sha256 = "abce70049aef585a149c5779c3c520ac69cd76542ed314bcd48ae95d4d2f5e13"
url = "https://image.fduhole.com/i/2025/05/23/683022b401a4fa.webp"

[[sticker]]
id = "dx_sleep"
sha256 = "66774d53254faee103e990f0d7b2e5d87fad688fb64758f554aa0594c8d8a3ee"
url = "https://image.fduhole.com/i/2025/05/23/683022b5f96cf5.webp"

[[sticker]]
id = "dx_confused"
sha256 = "95dfc13da9c4b85486a7124f4a049949c8074c3784aae3195af5cc6aa7de9b43"
url = "https://image.fduhole.com/i/2025/05/23/683022b52da70f.webp"

[[sticker]]
id = "dx_dying"
sha256 = "da3aef33798d44968282de9cad2bdbf542e4cf41d7bad845545225ad35d44e8a"
url = "https://image.fduhole.com/i/2025/05/23/683022b5ced5d6.webp"

[[sticker]]
id = "dx_roped"
sha256 = "5b4e57c8c00c831ece07c5a5d1a9ab4a8d974a18cc4b8d61abed4906fe1497ec"
url = "https://image.fduhole.com/i/2025/05/23/683022b56421ba.webp"

[[sticker]]
id = "dx_onfire"
sha256 = "e0d93ebd809308504d1d2356d596d279ba1dadfec2567206d470e0ef1b70fcc3"
url = "https://image.fduhole.com/i/2025/05/23/683022b5bc2f4e.webp"

[[sticker]]
id = "dx_onlooker"
sha256 = "31a97a9625117a8c9c4b654b6c7b079f08eb3cfabc61bfc2b0c414d16ed0ebfd"
url = "https://image.fduhole.com/i/2025/05/23/683022b54612aa.webp"

[[sticker]]
id = "dx_fright"
sha256 = "3e0b3addcc9470b57e047a963122f7c6f800d211fb3ebb0ddc362e934d6ad559"
url = "https://image.fduhole.com/i/2025/05/23/683022b5223c36.webp"

[[sticker]]
id = "dx_egg"
sha256 = "028408ae334860acf1b3f90115140dd189bf72d52d3b2c61e68621174b003094"
url = "https://image.fduhole.com/i/2025/05/23/683022b5468dfc.webp"

[[sticker]]
id = "dx_eatnow"
sha256 = "6cf53f042595b875dc007d8532a156c5138f431a9867a27d277d7ea7b7ca734e"
url = "https://image.fduhole.com/i/2025/05/23/683022b51f13a4.webp"

[[sticker]]
id = "dx_caught"
sha256 = "846b348d31e0e68a5626226f9eb636c929eb66f501ebbb2ed13975fc0d7d787f"
url = "https://image.fduhole.com/i/2025/05/23/683022b6056aa7.webp"

[[sticker]]
id = "dx_swim"
sha256 = "a92ad812fc0f31498e79f823a95247b2209dfc36ed19b4696eebed28b4a249ec"
url = "https://image.fduhole.com/i/2025/05/23/683022b6a843dd.webp"

[[sticker]]
id = "dx_cry"
sha256 = "d7b12f2974023ee909d33ffd1f1c0d7038dac5bc48ce2362c86817730fdb88da"
url = "https://image.fduhole.com/i/2025/05/23/683022b66d464a.webp"

[[sticker]]
id = "dx_heart"
sha256 = "c2d4e074778b45bd548e0569be8fe10cf7c5c7432daea1765956efa8eed1ffab"
url = "https://image.fduhole.com/i/2025/05/23/683022b6ad0b27.webp"

[[sticker]]
id = "dx_mokyu"
sha256 = "cfb9a86409d266f3e06a1f0d8065f198d99e9ea4a43a5d0444924917415c4d80"
url = "https://image.fduhole.com/i/2025/05/23/683022b6c3c328.webp"

[[sticker]]
id = "dx_craving"
sha256 = "b38c303bb2bdcd4f5d171460edc3e5f9e4f30f1536025ebe541a9cb31de23c2c"
url = "https://image.fduhole.com/i/2025/05/23/683022b64d820f.webp"

[[sticker]]
id = "dx_angry"
sha256 = "84329df7ffe797d37b5c1b07f2c0643371865bc5e4d553033815c87e414a7ac9"
url = "https://image.fduhole.com/i/2025/05/23/683022b6aa2d8a.webp"

[[sticker]]
id = "dx_elderphone"
sha256 = "ab6c85ac91a7eef9b45babbf2ed28ee90aaa2152bc803017954c5bd2f39505c9"
url = "https://image.fduhole.com/i/2025/05/23/683022b686bb4c.webp"

[[sticker]]
id = "dx_handsup"
sha256 = "a1df771b20ecbb5a6e51a663e1c3932ae7b6374e1c1f764dfad649107a0c445c"
url = "https://image.fduhole.com/i/2025/05/23/683022b7a7721f.webp"

[[sticker]]
id = "dx_overwhelm"
sha256 = "eacfad570a2561079e79002fe59f2eda5140aad2798e78bb5de187cabcbed031"
url = "https://image.fduhole.com/i/2025/05/23/683022b7308a40.webp"

[[sticker]]
id = "dx_ehe"
sha256 = "fd42aa51695fddcf4e61c2cd85ca638940fb4e7237f0b08e3dd3872d415aafac"
url = "https://image.fduhole.com/i/2025/05/23/683022b7ad225e.webp"

[[sticker]]
id = "dx_worn"
sha256 = "14aaef89e5f96ec86e7499adab3d64c0ec0199a25f14865b173c10dbf59285f0"
url = "https://image.fduhole.com/i/2025/05/23/683022b73b977f.webp"

[[sticker]]
id = "dx_hug"
sha256 = "e33c67131a72565759ac6be0d8a953116d6c9ba1a0281fa00b63fe355a983954"
url = "https://image.fduhole.com/i/2025/05/23/683022b7d96198.webp"

[[sticker]]
id = "dx_ok"
sha256 = "22b61d0210c1bfd769e8f66c486742e49ececadf5351dcc6fcd5282fd2a28d2b"
url = "https://image.fduhole.com/i/2025/05/23/683022b7e00faa.webp"

[[sticker]]
id = "dx_thrill"
sha256 = "aec335e4440d4ff05832df989094b4aba0bf8d9c0cd9bcf194162e2043416ab3"
url = "https://image.fduhole.com/i/2025/05/23/683022b8cf2506.webp"

[[sticker]]
id = "dx_twin"
sha256 = "86d50c688c5f7ddf2918cb8f64467c13208087369d018e19f9fae4c9f4e4ddcd"
url = "https://image.fduhole.com/i/2025/05/23/683022b87512be.webp"

[[sticker]]
id = "dx_emperor"
sha256 = "a25863b6677c3c3b88c820c247c56e0e92ff3a80a2486efd964915b5dcb08c0a"
url = "https://image.fduhole.com/i/2025/05/23/683022b86a4748.webp"

[[sticker]]
id = "dx_broke"
sha256 = "35156d020f377b1682517d0d4e1a2063836ce53a386f27c5221d077d64a93485"
url = "https://image.fduhole.com/i/2025/05/23/683022b840ed47.webp"

[[sticker]]
id = "dx_lgtm"
sha256 = "9bf516b7e200d774b73cdc42d223f13e7ecdc8b6a32e079fc3b5ac9bb101dcd2"
url = "https://image.fduhole.com/i/2025/05/23/683022b85b900b.webp"

[[sticker]]
id = "dx_covermouth"
sha256 = "5fe71f5135a5e7553d01ccdf52bbb493db191ae5f0c67cf85c8fc2e894cfe81b"
url = "https://image.fduhole.com/i/2025/05/23/683022b8d41412.webp"

[[sticker]]
id = "dx_like"
sha256 = "75b0ed36ca7cb1e7c6e23ab069fb0b3608483fee3117a31c18734dae5ad690f3"
url = "https://image.fduhole.com/i/2025/05/23/683022b87cb69a.webp"

[[sticker]]
id = "dx_speechless"
sha256 = "b7fa33ffd7bdc4a7344293d2ea8bac8ed46f8737738f6c9f5c32d6946424ba7e"
url = "https://image.fduhole.com/i/2025/05/23/683022b86fc48f.webp"

[[sticker]]
id = "dx_strong"
sha256 = "baf1e1455b79b9a7e74771154e71dd2870ec59c2a20c3d52b3aa6e5c0dd1d475"
url = "https://image.fduhole.com/i/2025/05/23/683022b87d6ad6.webp"

[[sticker]]
id = "dx_touch_fish"
sha256 = "a01453258481dc2544ac8225c1e58cfe0e8ff5bd1e1c9d2a7c5154fbd3168493"
url = "https://image.fduhole.com/i/2025/05/23/683022b9eb2e37.webp"

[[sticker]]
id = "dx_cate"
sha256 = "d08a15a7b8554d801661cdb45e44ef6f10f0ba20622957e96361dce484355df8"
url = "https://image.fduhole.com/i/2025/05/23/683022b9a779ef.webp"
